spring:
  security:
    oauth2:
      client:
        registration:
          google:
#    Check link for google http://localhost:8081/oauth2/authorization/google
#     Google Cloud Console
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
#    Check link for github http://localhost:8081/oauth2/authorization/github
#    development setting -> when deploy, have to go change the frontend link
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
#facebook http://localhost:8081/oauth2/authorization/facebook
#      Meta for developers
#            client-id: ${FACEBOOK_CLIENT_ID}
#            client-secret: ${FACEBOOK_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope: public_profile, email


        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v22.0/dialog/oauth
            token-uri: https://graph.facebook.com/v22.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,first_name,last_name,email,picture
            user-name-attribute: id